#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port4,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Forward until Close Proximity -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to drive forward at half speed until the Ultrasonic Sensor       *|
|*  detects an obstruction within 20 inches of it.                                                    *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  The Ultrasonic Sensor returns a value of '-1' when it is out of range from the nearest      *|
|*        object.  The range is from 0 to 255 inches, so make sure that the robot is within this      *|
|*        range or it may never run.                                                                  *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 4    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 6    leftMotor           VEX 3-wire module     Left side motor                   *|
|*																																																		*|
|*		Digital - Port 14,15   leftEncoder      VEX VEX Shaft Encoder Left side encoder                 *|
|*		Digital - Port 16,17   rightEncoder     VEX VEX Shaft Encoder Right side encoder                *|
|*    Digital - Port 8,9     sonarSensor       VEX Sonar Sensor      Front mounted, facing forward 		*|
|*																																																		*|
|*		Analog  - Port 8       lightSensor      VEX Light Sensor      Mounted facing up									*|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

const int BASEDIST = 11.12539408020152;
const int ROTATE = 90;
const float Dd = 2.559223300970874;
void drive(int dist, bool direct){							// Robot waits for 2000 milliseconds before executing program

		  // Set the encoder so that it starts counting at 0
	while(BASEDIST*dist > abs(SensorValue[rightEncoder]) )		// Creates an infinite loop, since "true" always evaluates to true
	{
		if(abs(SensorValue[rightEncoder]) == abs(SensorValue[leftEncoder])) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
		  if(direct == true){
			motor[rightMotor] = 80;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;
		 }// Left Motor is run at power level 80
		 else if(direct == false){
		   motor[rightMotor] = -80;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -80;
		 }
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]))	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right

			if(direct == true){
			motor[rightMotor] = 80;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 60;
		 }// Left Motor is run at power level 80
		 else if(direct == false){
		   motor[rightMotor] = -80;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -60;
		 }// Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
		  if(direct == true){
			motor[rightMotor] = 60;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;
		}
			else if(direct == false){
		   motor[rightMotor] = -60;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -80;
		 }// Left Motor is run at power level 80// Left Motor is run at power level 60
		}

		}
	}


void motorStop()
{
	motor[rightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 0;

	wait1Msec(500);

}

void resetEncoders(){
		SensorValue[rightEncoder] = 0;
	  SensorValue[leftEncoder]  = 0;
}
void Turn(bool direct, float rot)
{   /* consistancy and accuracy. */

	rot = rot * Dd;
  // While the encoders have not yet met their goal: (left is compared negativly since it will in reverse)
  //while(SensorValue[rightEncoder] < (r * rotations) && SensorValue[leftEncoder] > (-1 * r * rotations))
  if (direct == false){
	while(SensorValue[rightEncoder] < rot || SensorValue[leftEncoder] > -rot){
    motor[rightMotor] = 63;         // Run the right motor forward at half speed
    motor[leftMotor]  = -63;
  }
}
	else{
		while(SensorValue[leftEncoder] < rot || SensorValue[rightEncoder] > -rot){
		motor[rightMotor] = -63;         // Run the right motor forward at half speed
    motor[leftMotor]  = 63;
  }
  }
    // Run the left motor backward at half speed
           /* can act independantly as a "chunk" of code, without any loose ends. */
}

task main(){
while (true){
	if (SensorValue(lightSensor) < 100){
		if (SensorValue(sonarSensor) < 30){
			motorStop();
			Turn(false, ROTATE);
		}

		else{
				resetEncoders();
				drive(1, True);
		}

}
else{
	motorStop();
}
}

}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
