#pragma config(Motor,  port4,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)

const int time = 1050;
int CurrentTime = time;

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'leftMotor' (port 6) in the "Motors and Sensors Setup" is needed with the         *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*    3)  Drives forward and back in increasing increments and stops after he has gone 2.5 meters     *|
|*           																																													*|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 4        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 6        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void motorStop()
{
	motor[rightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 0;

	wait1Msec(1000);

}

task main()
{
	wait1Msec(1000);						// Robot waits for 2000 milliseconds before executing program

	for (int number = 1; number <= 5; number++)
	{

	// Move forward at full power for 3 seconds
	motor[rightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
	wait1Msec(CurrentTime);

	motorStop();

	motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power backward
	motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power backward
	wait1Msec(CurrentTime);

	motorStop();

	CurrentTime = CurrentTime + time;
}
	// Robot runs previous code for 3000 milliseconds before moving on
}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
