#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port4,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Moving Straight with Encoders -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program implements a self-straightening algorithm that provides a higher power level to the  *|
|*  motor that has traveled less, determined by comparing the values of the two encoders.             *|
|*  There is a 2 second pause at the beginning of the program.                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.					*|
|*		3) 	Drives forward and back in a straight line with encoders in 																*|
|*			 	increasing increments and stops after he has gone 2.5 meters	and back											*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 4    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 6    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 6,7  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 4,5  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/
const int BASEDIST = 11.12539408020152;
const int ROTATE = 90;
const float Dd = 2.559223300970874;
void drive(int dist, bool direct){							// Robot waits for 2000 milliseconds before executing program

		  // Set the encoder so that it starts counting at 0
	while(BASEDIST*dist > abs(SensorValue[rightEncoder]) )		// Creates an infinite loop, since "true" always evaluates to true
	{
		if(abs(SensorValue[rightEncoder]) == abs(SensorValue[leftEncoder])) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
		  if(direct == true){
			motor[rightMotor] = 80;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;
		 }// Left Motor is run at power level 80
		 else if(direct == false){
		   motor[rightMotor] = -80;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -80;
		 }
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]))	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right

			if(direct == true){
			motor[rightMotor] = 80;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 60;
		 }// Left Motor is run at power level 80
		 else if(direct == false){
		   motor[rightMotor] = -80;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -60;
		 }// Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
		  if(direct == true){
			motor[rightMotor] = 60;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;
		}
			else if(direct == false){
		   motor[rightMotor] = -60;		    // Right Motor is run at power level 80
			 motor[leftMotor]  = -80;
		 }// Left Motor is run at power level 80// Left Motor is run at power level 60
		}

		}
	}


void motorStop()
{
	motor[rightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 0;

	wait1Msec(500);

}

void resetEncoders(){
		SensorValue[rightEncoder] = 0;
	  SensorValue[leftEncoder]  = 0;
}
void Turn(bool direct, float rot)
{   /* consistancy and accuracy. */

	rot = rot * Dd;
  // While the encoders have not yet met their goal: (left is compared negativly since it will in reverse)
  //while(SensorValue[rightEncoder] < (r * rotations) && SensorValue[leftEncoder] > (-1 * r * rotations))
  if (direct == false){
	while(SensorValue[rightEncoder] < rot || SensorValue[leftEncoder] > -rot){
    motor[rightMotor] = 63;         // Run the right motor forward at half speed
    motor[leftMotor]  = -63;
  }
}
	else{
		while(SensorValue[leftEncoder] < rot || SensorValue[rightEncoder] > -rot){
		motor[rightMotor] = -63;         // Run the right motor forward at half speed
    motor[leftMotor]  = 63;
  }
  }
    // Run the left motor backward at half speed
           /* can act independantly as a "chunk" of code, without any loose ends. */
}
int dist = 50;
task main(){
{
	resetEncoders();

	drive(dist, true);

	motorStop();

	resetEncoders();

	Turn(false, ROTATE);

	motorStop();

	resetEncoders();

	drive(dist, true);

	motorStop();

	resetEncoders();

	Turn(true, ROTATE);

	motorStop();

	resetEncoders();

	drive(dist, true);

	motorStop();

	resetEncoders();

	Turn(true, ROTATE);

	motorStop();

	resetEncoders();

	drive(dist, true);

	motorStop();


}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
